//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Root</summary>
	[PublishedContentModel("root")]
	public partial class Root : PublishedContentModel, ICompositionContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "root";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Root(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Root, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Besøksadresse
		///</summary>
		[ImplementPropertyType("besoeksadresse")]
		public string Besoeksadresse
		{
			get { return this.GetPropertyValue<string>("besoeksadresse"); }
		}

		///<summary>
		/// Postadresse
		///</summary>
		[ImplementPropertyType("postadresse")]
		public string Postadresse
		{
			get { return this.GetPropertyValue<string>("postadresse"); }
		}

		///<summary>
		/// Telefon
		///</summary>
		[ImplementPropertyType("telefon")]
		public string Telefon
		{
			get { return this.GetPropertyValue<string>("telefon"); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IEnumerable<IPublishedContent> Banner
		{
			get { return Umbraco.Web.PublishedContentModels.CompositionContent.GetBanner(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return Umbraco.Web.PublishedContentModels.CompositionContent.GetDescription(this); }
		}

		///<summary>
		/// Grid
		///</summary>
		[ImplementPropertyType("grid")]
		public Newtonsoft.Json.Linq.JToken Grid
		{
			get { return Umbraco.Web.PublishedContentModels.CompositionContent.GetGrid(this); }
		}
	}
}
